"""initial schema: all core tables

Revision ID: 9dc2fd55b5fd
Revises: 
Create Date: 2026-03-11 22:33:46.696452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dc2fd55b5fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('monthly_story_limit', sa.Integer(), nullable=True),
    sa.Column('max_pages_per_story', sa.Integer(), nullable=True),
    sa.Column('image_quality_mode', sa.String(length=50), nullable=True),
    sa.Column('voice_clone_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_audio_chars_limit', sa.Integer(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_primary_email'), 'users', ['primary_email'], unique=True)
    op.create_table('assets',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('bucket_name', sa.String(length=100), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('asset_type', sa.Enum('PAGE_IMAGE', 'PAGE_AUDIO', 'VOICE_SAMPLE', 'COVER_IMAGE', 'THUMBNAIL', name='assettype'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('auth_identities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('PASSWORD', 'GOOGLE', 'APPLE', name='authprovider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_auth_provider_uid')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('children',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('favorite_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('favorite_characters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bedtime_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_user_id'), 'children', ['user_id'], unique=False)
    op.create_table('consents',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('consent_type', sa.Enum('TERMS_OF_SERVICE', 'PRIVACY_POLICY', 'VOICE_CLONING', 'CHILD_DATA', name='consenttype'), nullable=False),
    sa.Column('accepted_version', sa.String(length=50), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_voice_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('clone_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', 'DELETED', name='voiceprofilestatus'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('consent_confirmed', sa.Boolean(), nullable=False),
    sa.Column('default_for_user', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_user_id'), 'voice_profiles', ['user_id'], unique=False)
    op.create_table('character_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=True),
    sa.Column('reference_asset_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('visual_description', sa.Text(), nullable=True),
    sa.Column('style_notes', sa.Text(), nullable=True),
    sa.Column('canonical_traits_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reference_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_profiles_user_id'), 'character_profiles', ['user_id'], unique=False)
    op.create_table('stories',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('voice_profile_id', sa.Uuid(), nullable=True),
    sa.Column('cover_asset_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'READY', 'FAILED', 'DELETED', name='storystatus'), nullable=False),
    sa.Column('target_page_count', sa.Integer(), nullable=True),
    sa.Column('reading_level', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('art_style', sa.String(length=100), nullable=True),
    sa.Column('generation_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_child_id'), 'stories', ['child_id'], unique=False)
    op.create_index('ix_stories_user_child_status', 'stories', ['user_id', 'child_id', 'status'], unique=False)
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    op.create_table('voice_samples',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('voice_profile_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('sample_quality_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'ACCEPTED', 'REJECTED', name='voicesamplestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_samples_user_id'), 'voice_samples', ['user_id'], unique=False)
    op.create_index(op.f('ix_voice_samples_voice_profile_id'), 'voice_samples', ['voice_profile_id'], unique=False)
    op.create_table('story_characters',
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('character_profile_id', sa.Uuid(), nullable=False),
    sa.Column('role_in_story', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['character_profile_id'], ['character_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'character_profile_id', name='uq_story_character')
    )
    op.create_index(op.f('ix_story_characters_character_profile_id'), 'story_characters', ['character_profile_id'], unique=False)
    op.create_index(op.f('ix_story_characters_story_id'), 'story_characters', ['story_id'], unique=False)
    op.create_table('story_generation_jobs',
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('provider_text', sa.String(length=50), nullable=True),
    sa.Column('provider_image', sa.String(length=50), nullable=True),
    sa.Column('provider_audio', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_generation_jobs_story_id'), 'story_generation_jobs', ['story_id'], unique=False)
    op.create_table('story_pages',
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('continuity_notes', sa.Text(), nullable=True),
    sa.Column('image_asset_id', sa.Uuid(), nullable=True),
    sa.Column('audio_asset_id', sa.Uuid(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'TEXT_READY', 'IMAGE_READY', 'AUDIO_READY', 'COMPLETE', 'FAILED', name='storypagestatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'page_number', name='uq_story_page_number')
    )
    op.create_index(op.f('ix_story_pages_story_id'), 'story_pages', ['story_id'], unique=False)
    op.create_table('story_page_generations',
    sa.Column('story_page_id', sa.Uuid(), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=False),
    sa.Column('generation_type', sa.Enum('TEXT', 'IMAGE', 'AUDIO', name='generationtype'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('request_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['story_generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_page_id'], ['story_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_page_generations_generation_job_id'), 'story_page_generations', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_story_page_generations_story_page_id'), 'story_page_generations', ['story_page_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('story_id', sa.Uuid(), nullable=True),
    sa.Column('story_page_id', sa.Uuid(), nullable=True),
    sa.Column('usage_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_cost_micros', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_page_id'], ['story_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_index('ix_usage_records_user_type_created', 'usage_records', ['user_id', 'usage_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_records_user_type_created', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_story_page_generations_story_page_id'), table_name='story_page_generations')
    op.drop_index(op.f('ix_story_page_generations_generation_job_id'), table_name='story_page_generations')
    op.drop_table('story_page_generations')
    op.drop_index(op.f('ix_story_pages_story_id'), table_name='story_pages')
    op.drop_table('story_pages')
    op.drop_index(op.f('ix_story_generation_jobs_story_id'), table_name='story_generation_jobs')
    op.drop_table('story_generation_jobs')
    op.drop_index(op.f('ix_story_characters_story_id'), table_name='story_characters')
    op.drop_index(op.f('ix_story_characters_character_profile_id'), table_name='story_characters')
    op.drop_table('story_characters')
    op.drop_index(op.f('ix_voice_samples_voice_profile_id'), table_name='voice_samples')
    op.drop_index(op.f('ix_voice_samples_user_id'), table_name='voice_samples')
    op.drop_table('voice_samples')
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.drop_index('ix_stories_user_child_status', table_name='stories')
    op.drop_index(op.f('ix_stories_child_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_character_profiles_user_id'), table_name='character_profiles')
    op.drop_table('character_profiles')
    op.drop_index(op.f('ix_voice_profiles_user_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_children_user_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_primary_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    # ### end Alembic commands ###

    # Drop PostgreSQL ENUM types
    for enum_name in [
        'userstatus', 'authprovider', 'voiceprofilestatus', 'voicesamplestatus',
        'storystatus', 'storypagestatus', 'assettype', 'jobstatus',
        'generationtype', 'subscriptionstatus', 'consenttype',
    ]:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
